name: Elm CI
description: 'Elm setup'
author: 'Jaeyson'
branding:
  icon: 'download'
  color: 'green'

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:alpine

    steps:
      - uses: actions/checkout@v1
      - name: Install Elm
        run: |
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip elm.gz
          chmod +x elm
          sudo mv elm /usr/local/bin/

    steps:
      - name: Install elm-format & elm-test
        run: |
          npm install -g elm-format elm-test
          elm-format src/ --yes
          elm-test

